BEGIN TRANSACTION;
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`email`	TEXT UNIQUE,
	`password`	TEXT
);
DROP TABLE IF EXISTS `notes_permissions`;
CREATE TABLE IF NOT EXISTS `notes_permissions` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`user_id`	INTEGER NOT NULL,
	`note_id`	INTEGER NOT NULL
);
DROP TABLE IF EXISTS `notes`;
CREATE TABLE IF NOT EXISTS `notes` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`uuid`	TEXT NOT NULL UNIQUE,
	`content`	TEXT,
	`public`	INTEGER DEFAULT 0,
	`owner`	INTEGER NOT NULL
);
COMMIT;
